### ISSUE TITLE
Fix "Add a New Period"

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE-Portal--Deprecated--#6]
The period field needs validation. Right now teachers can add periods named "2,3" and can also add a period that already exists.

See if you can also delete the period "2,3" from Jeff Hartman's run 1139 which he accidentally created.

**Comment by hirokiterashima** [comment]
Fixed by validating in the client(js) side.

Committed:
https://github.com/WISE-Community/WISE-Portal/commit/af6c7e889232ad2d08bfccd10f8553845937b0da

Jeff Hartman's period "2,3" is group ID=42466. There was no student associated in that group.  

So I deleted [1139,42466] row from runs_related_to_groups table.
