### ISSUE TITLE
Home page does not render correctly anymore in Firefox

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE-Portal--Deprecated--#83]
We receive these errors now when loading the home page in Firefox. Do you know what's causing them?

TypeError: $("#newsContent").jScrollPane is not a function
[Break On This Error]   

$('#newsContent').jScrollPane();

index.html (line 77)

TypeError: $("#showcaseSlider").nivoSlider is not a function
[Break On This Error]   

afterChange: function(){

index.html (line 119)

**Comment by breity** [comment]
Yeah, I'm trying to figure this out.  I don't know what the problem is, as it doesn't seem like anything was changed.  The jQuery plugins (jScrollPane and nivoSlider) don't seem to be loading for some reason, even though it shows that they've loaded in Firebug.

**Comment by breity** [comment]
Fixed (partially): https://github.com/WISE-Community/WISE-Portal/commit/352f7e6ddcb93fe6ff61ac0e4a6056d9a45b7d73

Still getting some js errors and superfish menu isn't showing correct rollover styling on home page.  But functionality seems to work fine otherwise now that I moved js scripts to the bottom of the page.  Will revisit when the homepage is redesigned in the new year.
